/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTC1 (number 71), J1[5]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_mLp_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_mLp_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_mLp_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC2 (number 72), J1[14]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_mRp_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_mRp_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_mRp_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB19 (number 65), J1[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_mLs_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_mLs_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_mLs_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_mLs_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_mLs_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB18 (number 64), J1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_mRs_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_mRs_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_mRs_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_mRs_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_mRs_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB2 (number 55), J4[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_A0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_A0_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_A0_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTB3 (number 56), J4[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_A1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_A1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_A1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTB10 (number 58), J4[6]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_A2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_A2_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_A2_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB11 (number 59), J4[8]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_A3_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_A3_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_A3_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
